input {
  beats {
    port => 5044
  }
}

filter {

  # NGINX LOGS — from Ubuntu VM Filebeat
  if "nginx" in [tags] or "nginx" in [source] or "access" in [log][file][path] {

    grok {
      match => { "message" => "(?:%{IP:client_ip}|%{IPV6:client_ip}) %{DATA:ident} %{DATA:auth} \[%{HTTPDATE:timestamp}\] \"%{WORD:http_method} %{DATA:request_path} HTTP/%{NUMBER:http_version}\" %{NUMBER:status_code:int} %{NUMBER:response_size:int} \"%{DATA:referrer}\" \"%{DATA:user_agent}\"" }
    }

    date {
      match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
      target => "@timestamp"
    }

    mutate {
      convert => {
        "status_code" => "integer"
        "response_size" => "integer"
      }
      add_field => {
        "environment" => "lab"
        "server" => "nginx"
        "service_type" => "nginx"
      }
    }

    if [status_code] >= 400 {
      mutate { add_tag => ["error"] }
    }

    if [status_code] == 200 {
      mutate { add_tag => ["success"] }
    }
  }

  # MICROSERVICE LOGS — from Docker container Filebeat
  else if [container][name] == "checkout-microservice" {

    json {
      source => "message"
      target => "app"
    }

    mutate {
      add_field => {
        "service_type" => "microservice"
        "environment" => "lab"
      }
      add_tag => ["microservice", "checkout"]
    }

    if [app][level] == "ERROR" {
      mutate { add_tag => ["error"] }
    }

    if [app][level] == "WARNING" {
      mutate { add_tag => ["warning"] }
    }

    if [app][level] == "INFO" {
      mutate { add_tag => ["success"] }
    }
  }

  # WINDOWS LOGS — from Winlogbeat
  else {
    mutate {
      add_field => {
        "service_type" => "windows"
        "environment" => "lab"
      }
    }
  }

}

output {

  # NGINX → nginx index
  if [service_type] == "nginx" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "nginx-logs-%{+YYYY.MM.dd}"
    }
  }

  # MICROSERVICE → microservice index
  else if [service_type] == "microservice" {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "microservice-logs-%{+YYYY.MM.dd}"
    }
  }

  # WINDOWS → windows index
  else {
    elasticsearch {
      hosts => ["http://elasticsearch:9200"]
      index => "windows-logs-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}